# Generated by Django 4.2.4 on 2023-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=20)),
                ('refby', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('BronchoVascularMarking', models.CharField(max_length=10)),
                ('BronchoVascularMarkingSide', models.CharField(blank=True, max_length=10, null=True)),
                ('BronchoVascularMarkingRegion', models.CharField(blank=True, max_length=30, null=True)),
                ('opacity', models.CharField(max_length=10)),
                ('opacitySide', models.CharField(blank=True, max_length=10, null=True)),
                ('opacityRegion', models.CharField(blank=True, max_length=30, null=True)),
                ('cavity', models.CharField(max_length=10)),
                ('cavitySide', models.CharField(blank=True, max_length=10, null=True)),
                ('cavityRegion', models.CharField(blank=True, max_length=30, null=True)),
                ('masses', models.CharField(max_length=10)),
                ('massesSide', models.CharField(blank=True, max_length=10, null=True)),
                ('massesRegion', models.CharField(blank=True, max_length=30, null=True)),
                ('hilum', models.CharField(max_length=10)),
                ('hilumSide', models.CharField(max_length=10)),
                ('ProminentHilumSpecify', models.CharField(blank=True, max_length=30, null=True)),
                ('trachea', models.CharField(max_length=10)),
                ('tracheaShiftSide', models.CharField(blank=True, max_length=10, null=True)),
                ('mediastinal', models.CharField(max_length=10)),
                ('mediastinalShiftSide', models.CharField(blank=True, max_length=10, null=True)),
                ('LymphNodes', models.CharField(max_length=10)),
                ('CardiacSize', models.CharField(max_length=10)),
                ('CardiacShape', models.CharField(max_length=10)),
                ('CardiacShapeAbnormal', models.CharField(blank=True, max_length=30, null=True)),
                ('AorticKnuckle', models.CharField(max_length=10)),
                ('AorticKnuckleCalcification', models.CharField(max_length=10)),
                ('AorticKnuckleUnfoldingofAorta', models.CharField(max_length=10)),
                ('CostophrenicAngles', models.CharField(max_length=10)),
                ('CostophrenicAnglesSide', models.CharField(blank=True, max_length=10, null=True)),
                ('Pneumothorax', models.CharField(max_length=10)),
                ('PneumothoraxSide', models.CharField(blank=True, max_length=10, null=True)),
                ('BonyCage', models.CharField(max_length=10)),
                ('BonyCageSide', models.CharField(blank=True, max_length=10, null=True)),
                ('Finding', models.CharField(blank=True, max_length=30, null=True)),
                ('Bonylesion', models.CharField(blank=True, max_length=10, null=True)),
                ('FractureSide', models.CharField(blank=True, max_length=10, null=True)),
                ('FractureRibNumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SoftTissue', models.CharField(max_length=10)),
                ('SoftTissueSide', models.CharField(blank=True, max_length=10, null=True)),
                ('SoftTissueAbnormal', models.CharField(blank=True, max_length=30, null=True)),
                ('HemiDiaphragmSide', models.CharField(max_length=10)),
                ('HemiDiaphragm', models.CharField(max_length=10)),
                ('HemiDiaphragmAbormal', models.CharField(blank=True, max_length=30, null=True)),
                ('BreastShadow', models.CharField(max_length=10)),
                ('BreastShadowSide', models.CharField(blank=True, max_length=10, null=True)),
                ('BreastShadowAbnormal', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
